
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run-script build
            - run: tar -cvf build.tar ./build/
            - run: tar -rvf build.tar ./package.json
            - run: tar -rvf build.tar ./package-lock.json
      - store_artifacts:
          path: build.tar
          destination: built.tar
workflows:
    build:
      jobs:
        - build 
